twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 50
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 70
      arucomaker:
        topic   : cmd_vel_aruco
        timeout : 0.5
        priority: 30
      saftey:
        topic   : cmd_vel_safe
        timeout : 3.0
        priority: 200

    locks:
      saftey:
        topic   : safe_priority
        timeout : 0.0
        priority: 210
      control:
        topic   : control_priority
        timeout : 0.0
        priority: 100
