twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic   : cmd_vel_nav
        timeout : 0.5
        priority: 10
      joystick:
        topic   : cmd_vel_joy
        timeout : 0.5
        priority: 80
      arucomaker:
        topic   : cmd_vel_aruco
        timeout : 0.5
        priority: 50
      saftey:
        topic   : cmd_vel_safe
        timeout : 0.5
        priority: 100