<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="diffbot" params="prefix">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="4.0" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.260" />
  <xacro:property name="base_length" value="0.525" />
  <xacro:property name="base_height" value="0.060" />
  <xacro:property name="wheelbase" value="0.325" />
  <xacro:property name="wheel_mass" value="0.34055" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.045" />
  <xacro:property name="wheel_radius" value="0.05" />
  <xacro:property name="lidar_height" value="0.05" />
  <xacro:property name="lidar_radius" value="0.03" />

  <!-- <xacro:property name="wheeltrack" value="" -->

  <!-- Base Link -->
  <link name="${prefix}base_link" />
    <!-- <joint name= "base-chassis">
    <parent link="${prefix}base_link"/>
    <child link="${prefix}chassis_link"/>
    <joint/> -->

  <!-- Chassis -->

  <link name="${prefix}chassis_link">
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="white"/>
    </visual>

    <inertial>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <mass value="${base_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>
    </link>

    <joint name="${prefix}chassis_joint" type="fixed">
      <parent link="${prefix}base_link"/>
      <child link="${prefix}chassis_link"/>
      <origin xyz="0 0 ${base_height/2 + wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.2"/>
    </joint>

    <gazebo reference="${prefix}chassis_joint">
        <material>Gazebo/White</material>
    </gazebo>

    <!-- rear wheels -->

    <!-- rear right wheel -->

    <link name="${prefix}rear_right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>

    </link>

    <joint name="${prefix}rear_right_wheel_joint" type="continuous">
      <parent link="${prefix}chassis_link"/>
      <child link="${prefix}rear_right_wheel"/>
      <origin xyz="-${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="1.0"/>
      <dynamics damping="0.2"/>
    </joint>

    <gazebo reference="${prefix}rear_right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- rear left wheel -->
    <link name="${prefix}rear_left_wheel">
        <collision>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <geometry>
            <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <geometry>
            <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
          </geometry>
          <material name="black"/>
        </visual>

        <inertial>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <mass value="${wheel_mass}"/>
          <inertia
            ixx="0.000270" ixy="0.0" ixz="0.0"
            iyy="0.000270" iyz="0.0"
            izz="0.000426"/>
        </inertial>

    </link>

    <joint name="${prefix}rear_left_wheel_joint" type="continuous">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}rear_left_wheel" />
      <origin xyz="-${wheelbase/2} -${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="1.0"/>
      <dynamics damping="0.2"/>
    </joint>

    <gazebo reference="${prefix}rear_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- front wheels -->

    <!-- front right wheel -->


    <link name="${prefix}front_right_wheel">

      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>
    </link>

    <joint name="${prefix}front_right_wheel_joint" type="continuous">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}front_right_wheel" />
      <origin xyz="${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="1.0"/>
      <dynamics damping="0.2"/>
    </joint>

    <gazebo reference="${prefix}front_right_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- front left steering -->


    <link name="${prefix}front_left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <inertial>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <mass value="${wheel_mass}"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>

    </link>

    <joint name="${prefix}front_left_wheel_joint" type="continuous">
      <parent link="${prefix}chassis_link" />
      <child link="${prefix}front_left_wheel" />
      <origin xyz="${wheelbase/2} -${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="1.0"/>
      <dynamics damping="0.2"/>
    </joint>

    <gazebo reference="${prefix}front_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- IMU Sensor -->
    <link name="${prefix}imu_sensor">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.02 0.02"/>
        </geometry>
        <material name="blue"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <box size="0.02 0.02 0.02"/>
        </geometry>
      </collision>

      <inertial>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <mass value="0.01"/>
        <inertia
          ixx="0.000270" ixy="0.0" ixz="0.0"
          iyy="0.000270" iyz="0.0"
          izz="0.000426"/>
      </inertial>  

    </link>

    <joint name="${prefix}imu_joint" type="fixed">
      <parent link="${prefix}chassis_link"/>
      <child link="${prefix}imu_sensor"/>
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0"/>
    </joint>

    <gazebo reference="${prefix}laser">
        <material>Gazebo/Black</material>
    </gazebo>

    <!-- LiDAR Sensor -->
    <link name="${prefix}laser">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${lidar_height}" radius="${lidar_radius}"/>
        </geometry>
        <material name="green"/>
      </visual>

      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder radius="${lidar_height}" length="${lidar_radius}"/>
        </geometry>
      </collision>

    </link>

    <joint name="${prefix}laser_joint" type="fixed">
      <parent link="${prefix}chassis_link"/>
      <child link="${prefix}laser"/>
      <origin xyz="0 0 ${base_height/2 + lidar_height/2}" rpy="0 0 0"/>
    </joint>

    <!-- <xacro:include filename="lidar.xacro"/>
    <xacro:include filename="imu.xacro"/> -->
    <!-- Additional definitions for front wheels omitted for brevity -->
  </xacro:macro>

</robot>
